---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.6.0

platforms:
  # - name: ubuntu-14.04
  - name: centos-7.1
    driver_config:
      #box: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.1_chef-provisionerless.box
      network:
        - ["forwarded_port", {guest: 8080, host: 8081}]

suites:
  - name: centos-71
    data_bags_path: "~/.chef/data_bags" 
    run_list:
    - recipe[multi-server::default]
    # - recipe[chef-vault]
    # - recipe[multi-server::chef-vault-test]
    attributes:
    dev_mode: true
